# Generated by Django 5.2.5 on 2025-09-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_site_default_route_and_vehicle_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-route_date', 'definition']},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='sequence',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('definition', 'route_date')},
        ),
    ]
