# Generated by Django 5.2.5 on 2025-09-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_route_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='visit_frequency_days',
            field=models.PositiveIntegerField(default=7, help_text='How often this site should be visited, in days (e.g., 7 for weekly).'),
        ),
    ]
