# Generated by Django 5.2.5 on 2025-09-01 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_visit_frequency_to_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
