# Generated by Django 5.2.5 on 2025-09-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_change_collection_timestamp_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('route', 'site')},
        ),
    ]
