# Generated by Django 5.2.5 on 2025-09-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_stop_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='planned_fresh_oil_load',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fresh oil (in litres) to be loaded for this route, set by the planner.', max_digits=8),
        ),
    ]
