# Generated by Django 5.2.5 on 2025-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_move_planned_oil_to_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='actual_fresh_oil_loaded',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Actual fresh oil (in litres) loaded by the warehouse manager.', max_digits=8),
        ),
    ]
