# Generated by Django 5.2.5 on 2025-09-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_actual_fresh_oil_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteForLoading',
            fields=[
            ],
            options={
                'verbose_name': 'Route Loading Plan',
                'verbose_name_plural': 'Route Loading Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.route',),
        ),
    ]
