# Generated by Django 5.2.5 on 2025-09-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_routeforloading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyvehiclelog',
            name='start_day_fresh_oil',
        ),
    ]
