# Generated by Django 5.2.5 on 2025-09-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_simplify_daily_log_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='failure_reason',
            field=models.CharField(choices=[('NO_COLLECTION', 'Customer did not need a collection'), ('SHOP_CLOSED', 'Shop closed'), ('POOR_ACCESS', 'Poor access'), ('OTHER', 'Other (see notes)')], help_text='Reason for a failed stop', max_length=20),
        ),
    ]
