"""
Django settings for regency_oils project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4j!9v=n7abf*!z^$ejk7xdno^bl#nw3-n*vd)y)*!s@50xok^g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    # "unfold.contrib.filters",  # optional, if special filters are needed
    # "unfold.contrib.forms",  # optional, if special form elements are needed
    # "unfold.contrib.inlines",  # optional, if special inlines are needed
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'regency_oils.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # This 'DIRS' list tells Django to look in the main 'templates' folder
        'DIRS': [BASE_DIR / "templates"], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'regency_oils.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.CustomUser'

ALLOWED_HOSTS = [
    '8000-firebase-regency-oils-1755240935832.cluster-lu4mup47g5gm4rtyvhzpwbfadi.cloudworkstations.dev',
    '127.0.0.1',
]

CSRF_TRUSTED_ORIGINS = [
    'https://8000-firebase-regency-oils-1755240935832.cluster-lu4mup47g5gm4rtyvhzpwbfadi.cloudworkstations.dev'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}   

UNFOLD = {
    "SITE_TITLE": "Regency Oils",
    "SITE_HEADER": "Regency Oils",
    "SITE_SYMBOL": "local_shipping",
    "THEME": "light", # The demo uses the light theme
    "DASHBOARD_CALLBACK": "core.dashboard.planner_dashboard_callback",

    "STYLES": [
        lambda request: static("core/css/admin_overrides.css"),
        "https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css",
    ],
    "SCRIPTS": [
        "https://cdn.jsdelivr.net/npm/toastify-js",
    ],

    # --- THIS SECTION SETS THE DEMO'S COLORS ---
    "COLORS": {
        "primary": {
            "50": "#eef2ff",
            "100": "#e0e7ff",
            "200": "#c7d2fe",
            "300": "#a5b4fc",
            "400": "#818cf8",
            "500": "#6366f1", # This is the main accent color
            "600": "#4f46e5",
            "700": "#4338ca",
            "800": "#3730a3",
            "900": "#312e81",
            "950": "#1e1b4b"
        }
    },

    "SIDEBAR": {
        "navigation": [
            {
                "title": "Operations",
                "icon": "rocket_launch",
                "items": [
                    {
                        "title": "Plan Routes", # Planner's main page
                        "icon": "map",
                        "link": "/admin/core/route/", 
                    },
                    {
                        "title": "Loading Plans", # Manager's main page
                        "icon": "inventory_2",
                        "link": "/admin/core/routeforloading/", 
                    },
                    {
                        "title": "Route Definitions",
                        "icon": "pin_drop",
                        "link": "/admin/core/routedefinition/",
                    },
                ],
            },
            {
                "title": "Management",
                "icon": "business_center",
                "items": [
                    {
                        "title": "Customers",
                        "icon": "groups",
                        "link": "/admin/core/customer/",
                    },
                    {
                        "title": "Sites",
                        "icon": "location_city",
                        "link": "/admin/core/site/",
                    },
                    {
                        "title": "Vehicles",
                        "icon": "local_shipping",
                        "link": "/admin/core/vehicle/",
                    },
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "/admin/core/customuser/",
                    },
                ],
            },
            {
                "title": "Data Records",
                "icon": "assessment",
                "items": [
                    {
                        "title": "All Stops",
                        "icon": "pin_drop",
                        "link": "/admin/core/stop/",
                    },
                    {
                        "title": "All Collections",
                        "icon": "compost",
                        "link": "/admin/core/collection/",
                    },
                    {
                        "title": "Daily Vehicle Logs",
                        "icon": "inventory",
                        "link": "/admin/core/dailyvehiclelog/",
                    },
                ],
            },
        ],
    },
}